apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: ${k8s_cert_name}
  namespace: default
spec:
  secretName: ${k8s_cert_name}-tls
  IssuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: '*.${cloudflare_zone}'
  dnsNames:
  - ${cloudflare_zone}
  acme:
    config:
    - dns01:
        provider: cloudflare-dns
      domains:
      - '*.${cloudflare_zone}'
      - ${cloudflare_zone}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # The ACME server URL
    server: ${acme_server_url}
    # Email address used for ACME registration
    email: ${acme_email}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable HTTP01 validations
    dns01:
      providers:
        - name: cloudflare-dns
          cloudflare:
            email: ${cloudflare_email}
            apiKeySecretRef:
              name: ${k8s_secret_name}
              key: api-key