apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx-poc
spec:
  selector:
    matchLabels:
      app: nginx-poc
  replicas: 5 
  template:
    metadata:
      labels:
        app: nginx-poc
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-poc
spec:
  selector:
    app: nginx-poc
  ports:
  - name: http
    port: 80
    targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-poc
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - "*.miris.io"
    secretName: miris-io-tls
  rules:
  - host: tls.miris.io
    http:
      paths: 
      - path: /
        backend: 
          serviceName: nginx-poc
          servicePort: http
